#!/usr/bin/env bash
#
# sanitize-db.sh — Drupal database sanitization for local development.
#
# Runs automatically after every `ddev pull` via the post-import-db hook in
# .ddev/config.yaml, and can be run manually any time:
#
#   ddev exec bash .ddev/scripts/sanitize-db.sh
#
# What it does and why is documented in docs/pii-audit.md — every rule below
# maps to a finding in that audit. If you install a new module that stores
# user-submitted data (webform, commerce, CRM integrations, ...), re-run the
# PII audit and extend this script.
#
# This script is idempotent: running it twice does no additional harm.
#
# Generated by the ddev-setup skill. Project-specific rules were chosen
# during the PII audit on {{AUDIT_DATE}} against the {{ENVIRONMENT}} database.

set -eu -o pipefail

# ---------------------------------------------------------------------------
# Safety guard: refuse to run anywhere that isn't a DDEV web container.
# This makes the script structurally incapable of touching a remote/production
# database even if invoked by mistake.
# ---------------------------------------------------------------------------
if [ "${IS_DDEV_PROJECT:-}" != "true" ]; then
  echo "sanitize-db.sh: IS_DDEV_PROJECT != true — refusing to run outside a DDEV container." >&2
  exit 1
fi

echo "==> Sanitizing database for local development..."

# ---------------------------------------------------------------------------
# Base layer (always on): user accounts.
#
# drush sql:sanitize rewrites users_field_data.mail/init to user-<uid>@localhost
# and resets every password to the given value. Accounts stay functional for
# local login testing; real addresses and password hashes are gone.
# ---------------------------------------------------------------------------
drush sql:sanitize -y \
  --sanitize-email='user-%uid@localhost' \
  --sanitize-password='local-dev-password'

# ---------------------------------------------------------------------------
# Project-specific rules — from docs/pii-audit.md.
#
# The ddev-setup skill fills this section in based on the audit findings and
# the per-category decisions made with the user. The commented examples below
# show the common shapes; delete the ones that don't apply.
#
# IMPORTANT: when sanitizing a fieldable entity's field table, also sanitize
# its *_revision twin — revisions retain pre-edit PII.
# ---------------------------------------------------------------------------

# --- Webform submissions (decision: truncate) ------------------------------
# drush sql:query "TRUNCATE TABLE webform_submission_data"
# drush sql:query "TRUNCATE TABLE webform_submission"

# --- Core contact form messages (decision: truncate) -----------------------
# drush sql:query "TRUNCATE TABLE contact_message"

# --- Comment authors (decision: anonymize in place) ------------------------
# drush sql:query "UPDATE comment_field_data SET mail = CONCAT('comment-', cid, '@localhost'), name = CONCAT('commenter-', cid), hostname = '127.0.0.1' WHERE mail IS NOT NULL OR hostname <> ''"

# --- Watchdog / dblog (decision: truncate; contains IPs and usernames) -----
# drush sql:query "TRUNCATE TABLE watchdog"

# --- Sessions (decision: truncate; contains IPs and session tokens) --------
# drush sql:query "TRUNCATE TABLE sessions"

# --- Custom user profile fields (decision: anonymize; include revisions) ---
# drush sql:query "UPDATE user__field_phone SET field_phone_value = '555-0100'"
# drush sql:query "UPDATE profile__field_address SET field_address_address_line1 = '123 Example St', field_address_postal_code = 'A1A 1A1'"

# --- Commerce orders / billing profiles (decision: anonymize) --------------
# drush sql:query "UPDATE commerce_order SET mail = CONCAT('order-', order_id, '@localhost') WHERE mail IS NOT NULL"

# --- Keep real addresses for team accounts (optional whitelist) ------------
# Re-assert known team accounts after sql:sanitize scrambled them, so
# password-reset emails etc. still work locally via Mailpit.
# drush sql:query "UPDATE users_field_data SET mail = 'dev@example.com', init = 'dev@example.com' WHERE name = 'admin'"

# ---------------------------------------------------------------------------
# Flush caches so nothing cached pre-sanitization (rendered emails, tokens)
# survives.
# ---------------------------------------------------------------------------
drush cache:rebuild

echo "==> Database sanitized. See docs/pii-audit.md for what was covered."
