#!/usr/bin/env bash
#
# sanitize-db.sh — WordPress database sanitization for local development.
#
# Runs automatically after every `ddev pull` via the post-import-db hook in
# .ddev/config.yaml, and can be run manually any time:
#
#   ddev exec bash .ddev/scripts/sanitize-db.sh
#
# What it does and why is documented in docs/pii-audit.md — every rule below
# maps to a finding in that audit. If you install a new plugin that stores
# user-submitted data (forms, commerce, newsletters, CRM, ...), re-run the
# PII audit and extend this script.
#
# This script is idempotent: running it twice does no additional harm.
#
# Generated by the ddev-setup skill. Project-specific rules were chosen
# during the PII audit on {{AUDIT_DATE}} against the {{ENVIRONMENT}} database.

set -eu -o pipefail

# ---------------------------------------------------------------------------
# Safety guard: refuse to run anywhere that isn't a DDEV web container.
# This makes the script structurally incapable of touching a remote/production
# database even if invoked by mistake.
# ---------------------------------------------------------------------------
if [ "${IS_DDEV_PROJECT:-}" != "true" ]; then
  echo "sanitize-db.sh: IS_DDEV_PROJECT != true — refusing to run outside a DDEV container." >&2
  exit 1
fi

# Table prefix, resolved at runtime so the script survives prefix changes.
P="$(wp db prefix)"

# Team accounts whose real email addresses should be KEPT (comma-free,
# space-separated SQL-quoted list used in NOT IN clauses below). Local mail
# is routed to Mailpit by wp-config-local.php, so even kept addresses can't
# receive real mail from local. Leave empty to scramble every account.
KEEP_EMAILS="{{KEEP_EMAILS}}"   # e.g. "'dev@example.com','ops@example.com'"

echo "==> Sanitizing database for local development..."

# ---------------------------------------------------------------------------
# Base layer (always on): user accounts and comment authors.
# ---------------------------------------------------------------------------

# Users: scramble email + display identity, clear activation keys.
if [ -n "$KEEP_EMAILS" ]; then
  wp db query "UPDATE ${P}users SET user_email = CONCAT('user-', ID, '@example.test'), user_activation_key = '' WHERE user_email NOT IN ($KEEP_EMAILS)"
else
  wp db query "UPDATE ${P}users SET user_email = CONCAT('user-', ID, '@example.test'), user_activation_key = ''"
fi

# Passwords: reset every account to a known local-dev password.
# (MD5 is fine here — WordPress upgrades the hash on first successful login.)
wp db query "UPDATE ${P}users SET user_pass = MD5('local-dev-password')"

# Usermeta: scrub common PII-bearing keys (billing/shipping from WooCommerce,
# phone fields, session tokens which embed IPs and user agents).
wp db query "DELETE FROM ${P}usermeta WHERE meta_key = 'session_tokens'"
wp db query "UPDATE ${P}usermeta SET meta_value = '' WHERE meta_key LIKE 'billing\\_%' OR meta_key LIKE 'shipping\\_%' OR meta_key LIKE '%phone%'"

# Comments: anonymize author email/IP/url; keep content and threading intact.
wp db query "UPDATE ${P}comments SET comment_author_email = CONCAT('comment-', comment_ID, '@example.test'), comment_author_IP = '127.0.0.1', comment_author_url = '' WHERE comment_author_email <> ''"

# ---------------------------------------------------------------------------
# Project-specific rules — from docs/pii-audit.md.
#
# The ddev-setup skill fills this section in based on the audit findings and
# the per-category decisions made with the user. The commented examples below
# show the common shapes; delete the ones that don't apply.
# ---------------------------------------------------------------------------

# --- Gravity Forms entries (decision: truncate) ----------------------------
# wp db query "TRUNCATE TABLE ${P}gf_entry_meta"
# wp db query "TRUNCATE TABLE ${P}gf_entry_notes"
# wp db query "TRUNCATE TABLE ${P}gf_entry"

# --- WPForms entries (decision: truncate) ----------------------------------
# wp db query "TRUNCATE TABLE ${P}wpforms_entry_fields"
# wp db query "TRUNCATE TABLE ${P}wpforms_entries"

# --- Ninja Forms submissions (decision: delete posts + truncate nf3) -------
# wp post delete $(wp post list --post_type=nf_sub --format=ids) --force 2>/dev/null || true

# --- Contact Form 7 + Flamingo stored messages (decision: delete) ----------
# wp post delete $(wp post list --post_type=flamingo_inbound --format=ids) --force 2>/dev/null || true
# wp post delete $(wp post list --post_type=flamingo_contact --format=ids) --force 2>/dev/null || true

# --- Fluent Forms submissions (decision: truncate) --------------------------
# wp db query "TRUNCATE TABLE ${P}fluentform_entry_details"
# wp db query "TRUNCATE TABLE ${P}fluentform_submissions"

# --- WooCommerce customers/orders (decision: anonymize) ---------------------
# wp db query "UPDATE ${P}wc_order_addresses SET first_name = 'Local', last_name = CONCAT('Customer-', order_id), email = CONCAT('order-', order_id, '@example.test'), phone = '555-0100', address_1 = '123 Example St', address_2 = '', postcode = 'A1A 1A1'"
# wp db query "UPDATE ${P}wc_orders SET billing_email = CONCAT('order-', id, '@example.test'), ip_address = '127.0.0.1' WHERE billing_email IS NOT NULL"
# wp db query "UPDATE ${P}wc_customer_lookup SET first_name = 'Local', last_name = CONCAT('Customer-', customer_id), email = CONCAT('customer-', customer_id, '@example.test')"
# wp db query "UPDATE ${P}postmeta SET meta_value = '' WHERE meta_key LIKE '\\_billing\\_%' OR meta_key LIKE '\\_shipping\\_%'"
# wp db query "TRUNCATE TABLE ${P}woocommerce_sessions"

# --- MailPoet subscribers (decision: truncate) ------------------------------
# wp db query "TRUNCATE TABLE ${P}mailpoet_subscribers"

# --- Security/audit log plugins (decision: truncate; contain IPs/usernames) -
# wp db query "TRUNCATE TABLE ${P}aiowps_audit_log"
# wp db query "TRUNCATE TABLE ${P}wsal_occurrences"

# ---------------------------------------------------------------------------
# Flush the object cache so nothing cached pre-sanitization survives.
# ---------------------------------------------------------------------------
wp cache flush

echo "==> Database sanitized. See docs/pii-audit.md for what was covered."
